name: 'units-test'
on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  # unit tests
  units:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm ci
      - run: npm testz
  # e2e tests
  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: ./
        id: test
        with:
          api-key: ${{ secrets.RAPID_API_KEY }}
          name: opt
      - run: |
          echo ${{ steps.test.ouputs.expired }}
          echo ${{ steps.test.ouputs.expirationDate }}
          echo ${{ steps.test.ouputs.daysBeforeExpiration }}
